---
title: "Welcome to Genomic Insights"
author: "Ding Yang Wang"
date: "`r Sys.Date()`"
format:
  html:
    css: styles.css
---

```{r, echo=FALSE}
```

# Welcome to Genomic Insights

This website is my personal note compilation, based on the **statistical foundations and machine learning applications in genomics** course. If you are interested in the application of **statistic**, **spatial omics**, **multi omics**, **ML/DL in bioinformatics**, you may find this resource helpful!

The course consists of a series of **theoretical lectures and programming exercises**, with a primary focus on analysis using **R** and **Python**. However, in my notes, I will mainly cover **fundamental theoretical concepts** and explain **the reasoning behind each step** rather than focusing on code implementation.

# About the Course

The **Compgen2025** course is organized by the **Max Delbrück Center** at the **Berlin Institute for Medical Systems Biology**. It is designed for **computational biology PhD students**, **experimental biologists**, and **medical scientists** who want to enhance their skills in data analysis.

🔗 [**More details about the course here**](https://compgen.mdc-berlin.de/)

# Course Notes

-   **Module 1**: AI-assisted data analysis

    1.  Statistics for Genomics - [Notes](module1/statistics.qmd), [Course record](https://www.youtube.com/playlist?list=PL7WXGPJM2P8b3f_8QvUIlrO3t_bJpAXxc), [Book Link](http://compgenomr.github.io/book/stats.html)

    2.  Unsupervised Learning - [Notes](module1/unsupervised.qmd), [Course record](https://www.youtube.com/playlist?list=PL7WXGPJM2P8Y-l6Vm3kpC9emTtk4HkNcT), [Book Link](http://compgenomr.github.io/book/unsupervisedLearning.html)

    3.  Supervised Learning - [Notes](module1/supervised.qmd), [Course record](https://www.youtube.com/playlist?list=PL7WXGPJM2P8YgHQeTqIC1eFcrchpBvA8g), [Book Link](http://compgenomr.github.io/book/supervisedLearning.html)

-   **Module 2**: Spatial omics data analysis

    1.  Introduction of Spatial Transcriptomics - [Notes](module2/Introduction_of_Spatial_Transcriptomics.qmd)

    2.  Spatial Transcriptomics Analysis - [Notes](module2/Spatial_Transcriptomics_Analysis.qmd)

    3.  Spatial Multiomics Integration - [Notes](module2/Multiomics_Integration.qmd)

    -   [lesson GitHub Link](https://github.com/BIMSBbioinfo/VoltRon?tab=readme-ov-file#installation)

-   **Module 3**: Multi-omics data integration and Neural Network

    1.  Introduction of Multiomics - [Notes](module3/Introduction_of_Multiomics.qmd), [Course record](https://www.youtube.com/watch?v=7QxRqhFDJiY&ab_channel=BoraUyar), [Slides](https://docs.google.com/presentation/d/1Z3m8JOQY0JidM7gIJNFWaOfCaTH-rU47y4zCu5Bk6mE/edit)

    2.  Neural Network Training - [Notes](module3/Neural_network_training.qmd), [Course record](https://www.youtube.com/watch?feature=shared&v=CjTjcu_k2EI), [Slides](https://docs.google.com/presentation/d/1a31RoNIiZYdZFL9cc4OZ3TpgBGrk1IH1brW9VeHo3dQ/edit)

    3.  Genomics Model - [Notes](module3/Genomics_Model.qmd), [Course record](https://www.youtube.com/watch?feature=shared&v=WM4VkjFHOwI), [Slides](https://docs.google.com/presentation/d/1OvXK4H5W7qbD4jeru8pwnkQdiGz0RfjrW4Omd8kd0dg/edit) (In the note, I used lots of supplyments. Therefore, it might be different from the course record)

    -   [lesson GitHub Link](https://github.com/BIMSBbioinfo/compgen_course_2025_module3)

# Practical Applications

In addition to the theoretical notes, I also worked on several hands-on projects during the course, applying the concepts to real-world problems in computational genomics. Below are some of the complete analyses I conducted:

## Visium Analysis

-   The markdown is using **10X Visium data (Mouse Brain)** and covers normalization, dimensionality reduction, clustering, visualization, and integration with single-cell data for deconvolution and cell type inference.
-   [Code](module2/Visium-analysis.html)

## Xenium Analysis

-   Xenium is a **cell-level spatial transcriptomics platform** that offers subcellular resolution. This allows us to examine not just spatial zones of gene expression but **individual cells and their microenvironments**. Here, we perform a full analysis including: data filtering, disk-based representation for large-scale handling, clustering, marker analysis, and hotspot detection.
-   [Code](module2/Xenium-analysis.html)

## Xenium Analysis with Image Registration

-   Registered multimodal images (cell assays, molecular assays, H&E, ROI) to integrate spatial and morphological features. Studied spatially resolved gene expression and microenvironment interactions.
-   [Code](module2/Image-Registration.html)

## Breast Cancer Subtype Prediction

-   Integrated METABRIC multi-omics data (gex, cna, clinical); selected features with Laplacian score; trained model with Bayesian hyperparameter tuning; evaluated classification performance.
-   [Code](https://github.com/Dewey-Wang/Compgen-2025/blob/main/code/module%203/hw/day%201/noteboook/day1_hw_brca_subtypes.ipynb)

## Survival Analysis

-   Integrated TCGA LGG/GBM data (mutation, cna, clinical); performed EDA; built survival models targeting OS STATUS/OS MONTHS; computed top 5 features with Integrated Gradients; built Cox-PH model with markers and clinical variables; visualized log hazard ratios.
-   [Code](https://github.com/Dewey-Wang/Compgen-2025/blob/main/code/module%203/hw/day%202/noteboook/day2_hw_lgg_gbm.ipynb)

## Drug Response Prediction

-   Integrated CCLE/GDSC data (mutation, rna) to build models predicting Erlotinib responses; enhanced neural network models by incorporating STRINGDB protein network with Bayesian hyperparameter tuning; computed top 10 features with Integrated Gradients for correlation analysis.
-   [Code](https://github.com/Dewey-Wang/Compgen-2025/blob/main/code/module%203/hw/day%203/noteboook/day3.ipynb)

# Acknowledgments

First of all, I would like to express my heartfelt gratitude to the Scientific Organization, especially to **Dr. Altuna Akalın** from the **Max Delbrück Center**, for organizing this course. I am also deeply thankful to **Dr. Artür Manukyan, Dr. Bora Uyar**, and all the other instructors for their valuable contributions. This course is highly beneficial for those interested in **machine learning and bioinformatics**, providing a strong foundation in these fields.
